# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Personal
    url: /personal/
    weight: 15
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
